name: Deploy to Firebase

on: 
  push:
    branches:    
      - master
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, test and deploy
      run: |
        npm ci
        npm run build --if-present
        npm test
        npm run deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        CI: true
